server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:login_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret: "***REMOVED***"
  expiration: 3600000 # 1 saat (ms il?)

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true